# -*- coding: utf-8 -*-
"""Volcano List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z8RrS3iFoMGJA6gY7tC4MOUWlvkCywoc

# Code with me: Data Exploration with Pandas using Volcano.csv file
"""

# Target Age Group: Teens with Python coding background

"""Note: This dataset has no date of last eurption.  it is a list of known volcano with location data on on global volcanic hazard, historical events, population exposure, vulnerability, and impact has been provided to GAR15 by Global Volcano Model (GVM) and The International Association of Volcanology and Chemistry of the Earth’s Interior (IAVCEI).

Download data from <a href="https://data.humdata.org/dataset/a60ac839-920d-435a-bf7d-25855602699d">here</a>

# Panda Cheatsheet
"""

# Pandas Basic
# http://datacamp-community-prod.s3.amazonaws.com/dbed353d-2757-4617-8206-8767ab379ab3

# Pandas Data Wrangling
# https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

"""## How to use Pandas to read CSV file?"""

import pandas as pd
df = pd.read_csv("volcano.csv")
df

"""## What is a Pandas DataFrame?"""

df.info()

"""## How to get the list of unique values from a Column?"""

# how many volcano in each region
df["Region"].value_counts()

"""## How to select data subset from DataFrame?"""

df[df.Country == 'Indonesia']

"""## How to save to CSV file using Pandas?"""

indon = df[df.Country == 'Indonesia']
indon.to_csv("indonesia_v.csv")

"""# Map with Geographical Information

## How to embed a map in Notebook?
"""

import folium

# The default tiles are set to OpenStreetMap, but Stamen Terrain, Stamen Toner, Mapbox Bright, and Mapbox Control Room, and many others tiles are built in.

m = folium.Map(location=[5.5236, 95.6750], tiles='Stamen Terrain', zoom_start=5)
m

"""## How to add a map marker?"""

tooltip = 'Click me!'
		
# test
folium.Marker([3.170, 98.392], popup='<i>Mt Sinabung in Sumatra</i>', tooltip=tooltip).add_to(m)
folium.Marker([0.070, 127.420], popup='<b>Mt Tigalalu in Halmahera</b>', tooltip=tooltip).add_to(m)
m

"""# DataFrame: Subset

## How to get the count of records from a DataFrame?
"""

indon.VolcanoID.count()

"""## How to get each row of record by the index?"""

indon.iloc[0]

"""## How to get the attribute from a Python object?"""

indon.iloc[0].Latitude

"""# Use a FOR loop

## Test with 5 Markers
"""

# lets use a for loop
tooltip = 'Click me!'

total = indon.VolcanoID.count()

for index in range(total):
    record = indon.iloc[index]

    lat       = record.Latitude
    lon       = record.Longitude
    vname     = record.V_Name
    subregion = record.Subregion

    formatted = "<i>Mt {} in {}</i>".format(vname, subregion)

    folium.Marker([lat, lon], popup=formatted, tooltip=tooltip).add_to(m)
    if index == 5: break # test 5 markers

m

"""## Complete Codes"""

# complete codes
import folium

# The default tiles are set to OpenStreetMap, but Stamen Terrain, Stamen Toner, Mapbox Bright, and Mapbox Control Room, and many others tiles are built in.

m = folium.Map(location=[5.5236, 95.6750], tiles='Stamen Terrain', zoom_start=5)
tooltip = 'Click me!'

total = indon.VolcanoID.count()

for index in range(total):
    record = indon.iloc[index]

    lat       = record.Latitude
    lon       = record.Longitude
    vname     = record.V_Name
    subregion = record.Subregion

    formatted = "<i>Mt {} in {}</i>".format(vname, subregion)

    folium.Marker([lat, lon], popup=formatted, tooltip=tooltip).add_to(m)
    # if index == 5: break # test 5 markers

m

"""# Coding Challenge"""

# we have completed the map for Indonesia.

# challenge
# can you do the map for all the volcanoes in the world?